#Писать результат в локал?
#true, false
Enable local: true
#A integer
Radius local: 200

#Стандароно /roll в промежутке 1 & 20, кастомное значение:
Faces: 20

#Сообщения о результате (&p = player, &f = max number (faces), &b = bonus/malus, &n = number of /roll )
Result: '&p §fвыбил &n на кубике с &f гранями'
Result with bonus: '&p §fвыбил &n на кубике с &f гранями плюс &b'
Result with malus: '&p §fвыбил &n на кубике с &f гранями минус &b'