#Писать результат в локал?
#true, false
Enable local: true
#Радиус, если true
Radius local: 200

#Стандароно /roll в промежутке 1 & 20, кастомное значение:
Faces: 20

#Сообщения о результате (&p = игрок, &f = грани, &b = плюс/минус, &n = число )
Result: '&p §fвыбил &n на кубике с &f гранями'
Result with bonus: '&p §fвыбил &n на кубике с &f гранями &b'
Result with malus: '&p §fвыбил &n на кубике с &f гранями &b'