#Roll - plugin by LotuxPunk
#Source code : https://github.com/LotuxPunk/Roll
#Enjoy ! Amusez-vous !

#Display result in a local area ?
#true, false
Enable local: true
#A integer
Radius local: 30

#/roll sort a number between 1 & 20 by default, set your default max number :
Faces: 20

#Result sentence (&p = player, &f = max number (faces), &b = bonus/malus, &n = number of /roll )
Result: '&p §fa obtenu &n sur un dé à &f faces'
Result with bonus: '&p §fa obtenu &n sur un dé à &f faces, avec un bonus de &b'
Result with malus: '&p §fa obtenu &n sur un dé à &f faces, avec un malus de &b'