name: AnicloudRoll
main: com.vandendaelen.roll.Roll
version: 1.4.3
author: Amitexing & LotuxPunk
website: https://anicloud.ru
commands:
  roll:
    description: Выпадает случайное число в промежутке.
    usage: /roll [максимальное число] [-][число плюс/минус]
    aliases: [r]