name: Roll
main: com.vandendaelen.roll.Roll
version: 1.3
author: LotuxPunk
website: http://vandendaelen.com/
commands:
  roll:
    description: Donne un chiffre random a un gars lambda.
    usage: /roll [nombre max] [-][nombre bonus/malus]
    aliases: [r]