name: Roll
main: com.vandendaelen.roll.Roll
version: 1.4
author: LotuxPunk
website: https://github.com/LotuxPunk/Roll
commands:
  roll:
    description: Donne un chiffre random a un gars lambda.
    usage: /roll [nombre max] [-][nombre bonus/malus]
    aliases: [r]